language: node_js
node_js:
  - 12.13.0

before_install:
  - npm install

deploy:
  skip_cleanup: true
  provider: script
  script: npm run build-deploy
  on:
    tags: true

env:
  EXTENSION_ID=cohclepbfkicjacnladehmbiepoaobmm